export const DEFAULT_WALKIN_BLOCK_MINUTES = 120;
export const WALKIN_EXTEND_INCREMENT_MINUTES = 60;
export const WALKIN_EXTEND_LEAD_MINUTES = 10;
export const HOLD_DURATION_MINUTES = 5;
export const ONLINE_REQUEST_EXPIRY_MINUTES = 30;
